name: Kali Web (noVNC + Cloudflare Tunnel)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  kali-web:
    runs-on: ubuntu-latest
    container:
      image: pushpenderindia/kali-linux-novnc
      options: --user root
    timeout-minutes: 300
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Kali web env (noVNC + tunnel)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          chmod +x ./start.sh
          ./start.sh